language: objective-c
osx_image: xcode7.3
cache:
  directories:
  - $HOME/.macports-ci-ccache

matrix:
  include:
# I test all the combinations of:
# no mpi / openmpi / mpich
# native compilers / latest stable gcc
  - env: PLUMED_VAR=""               GROMACS_VAR=""
  - env: PLUMED_VAR="+allmodules"    GROMACS_VAR=""
  - env: PLUMED_VAR="+gcc6"          GROMACS_VAR="+gcc6"
  - env: PLUMED_VAR="+openmpi"       GROMACS_VAR="+openmpi"
  - env: PLUMED_VAR="+gcc6 +openmpi" GROMACS_VAR="+gcc6 +openmpi"
  - env: PLUMED_VAR="+mpich"         GROMACS_VAR="+mpich"
  - env: PLUMED_VAR="+gcc6 +mpich"   GROMACS_VAR="+gcc6 +mpich"

install:
# set columns in terminal, required for curl to work correctly:
 - export COLUMNS=80
 - wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
 - chmod +x ./macports-ci
 - ./macports-ci install
 - export PATH=/opt/local/bin:$PATH
 - ./macports-ci ccache
 - ./macports-ci localports "$PWD"

script:
# travis wait is needed since building mpi could require time
 - travis_wait 30 sudo port install plumed-devel $PLUMED_VAR
 - plumed info --configuration
 - travis_wait 30 sudo port install gromacs-plumed $GROMACS_VAR
 - ./macports-ci ccache --save
