language: objective-c
osx_image: xcode7.3

matrix:
  include:
# I test all the combinations of:
# no mpi / openmpi / mpich
# native compilers / latest stable gcc
  - env: PLUMED_VAR=""               GROMACS_VAR=""
  - env: PLUMED_VAR="+gcc6"          GROMACS_VAR="+gcc6"
  - env: PLUMED_VAR="+openmpi"       GROMACS_VAR="+openmpi"
  - env: PLUMED_VAR="+gcc6 +openmpi" GROMACS_VAR="+gcc6 +openmpi"
  - env: PLUMED_VAR="+mpich"         GROMACS_VAR="+mpich"
  - env: PLUMED_VAR="+gcc6 +mpich"   GROMACS_VAR="+gcc6 +mpich"

install:
# set columns in terminal, required for curl to work correctly:
 - export COLUMNS=80
 - wget https://raw.githubusercontent.com/GiovanniBussi/travis-ci-macports/master/install.macports
 - chmod +x install.macports
 - ./install.macports
 - export PATH=/opt/local/bin:$PATH
 - wget https://raw.githubusercontent.com/GiovanniBussi/travis-ci-macports/master/config.macports
 - chmod +x config.macports
 - ./config.macports "$PWD"

script:
# travis wait is needed since building mpi could require time
 - travis_wait sudo port install plumed $PLUMED_VAR
 - travis_wait sudo port install gromacs +plumed $GROMACS_VAR
