language: objective-c

matrix:
  include:
# I test all the combinations of:
# no mpi / openmpi / mpich
# native compilers / latest stable gcc
  - env: PLUMED_VAR=""               GROMACS_VAR=""
  - env: PLUMED_VAR="+gcc6"          GROMACS_VAR="+gcc6"
  - env: PLUMED_VAR="+openmpi"       GROMACS_VAR="+openmpi"
  - env: PLUMED_VAR="+gcc6 +openmpi" GROMACS_VAR="+gcc6 +openmpi"
  - env: PLUMED_VAR="+mpich"         GROMACS_VAR="+mpich"
  - env: PLUMED_VAR="+gcc6 +mpich"   GROMACS_VAR="+gcc6 +mpich"

install:
# set rows, columns in terminal, required for curl to work correctly:
 - stty rows 40 columns 80
# set path for macports
 - export MP_PREFIX=/opt/plumed
 - wget https://distfiles.macports.org/MacPorts/MacPorts-2.3.4.tar.bz2
 - tar xvfj MacPorts-2.3.4.tar.bz2
 - cd MacPorts-2.3.4 && ./configure --prefix=$MP_PREFIX --with-applications-dir=$MP_PREFIX/Applications && sudo make install
 - cd -
 - sudo rm -fr MacPorts-2.3.4
 - export PATH=$MP_PREFIX/bin:$PATH
 - sudo port -v selfupdate
 - ./.travis/config.sh

script:
# travis wait is needed since building mpi could require time
 - travis_wait sudo port install plumed $PLUMED_VAR
 - sudo port mdmg
 - sudo work plumed
 - travis_wait sudo port install gromacs +plumed $GROMACS_VAR

