language: objective-c

matrix:
  include:
  - env: PLUMED_VAR=""               GROMACS_VAR=""
  - env: PLUMED_VAR="+gcc6"          GROMACS_VAR="+gcc6"
  - env: PLUMED_VAR="+openmpi"       GROMACS_VAR="+openmpi"
  - env: PLUMED_VAR="+gcc6 +openmpi" GROMACS_VAR="+gcc6 +openmpi"
  - env: PLUMED_VAR="+mpich"         GROMACS_VAR="+mpich"
  - env: PLUMED_VAR="+gcc6 +mpich"   GROMACS_VAR="+gcc6 +mpich"

install:
# set rows, columns in terminal, required for curl to work correctly:
 - stty rows 40 columns 80
 - wget https://distfiles.macports.org/MacPorts/MacPorts-2.3.4.tar.bz2
 - tar xvfj MacPorts-2.3.4.tar.bz2
 - cd MacPorts-2.3.4 && ./configure && sudo make install
 - cd -
 - sudo rm -fr MacPorts-2.3.4
 - export PATH=/opt/local/bin:$PATH
 - sudo port -v selfupdate
 - ./.travis/config.sh

script:
 - sudo port install plumed $PLUMED_VAR
 - sudo port install gromacs +plumed $GROMACS_VAR
